GET https://quickbooks.api.intuit.com/v3/company/9341455470636484/query?query=select * from Item
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwieC5vcmciOiJIMCJ9..EQ7czRpVXR_onyDgP2t2Sg.mx8nyTV90D8YNxZzW-oE6VwccmuYg9_wAU7_3CTtppo2rp153qzi-5JUvbI_2P0-Vk8UwT0ZcxmdVz5UEBWAwVFXau69tAA4fMqRxJ0At-PXhUFmZrBvkO4JmPYKhHiQKVYZj7oFS1JZev91Rqgy52TL6IbSnmd1l1CwcXx745sIC2SO4Rtd5dVdPNZEZ3TYXL5Qlqt0F4NhBz5wMgKbbcQ2-PLz_sQCJxGwPLuoE8EZeecNQIKWXV7ASvEpSOU_noqsacZuaR1AGKXmn8ttqNfWSNG_VqIfLRlKUbT2b6C3ZxoM9jKwzsuXRukS0wi7ZXbvQSJVggG1Rp2HkkxONtC-KnQrShTnC-qhwBzf5s08X8i9UiMdgYQP2YKVkueI7UbnxLuz5kQzDzDSeMCKxaR5vlWQG-q8zE0SwwTyGDdBpN6nIji1O_oWw-7MwQAthvdisrkZ9bcBg3p_ZVyNPImq46vNo1VxBMzo3SpxA6M.2OCSNB2zavZM6pXeFW1LyQ
Content-Type: application/json
